### ISSUE TITLE
CSP issues with <script>${documentMonetizationPolyfill}</script> injection

### ISSUE THREAD

**Issue by sublimator** [WICG/webmonetization#137] opened 2020-11-05 04:02 UTC
See: https://github.com/coilhq/web-monetization-projects/issues/1248

- [ ] publish a new version of the extension/add-on that sends the messages as expected.  
- [ ] update the documentation with the CSP workaround of including the polyfill

**Comment by wmurphyrd** [comment] 2020-11-24 00:10
I published a [web-monetization-polyfill](https://www.npmjs.com/package/web-monetization-polyfill) package on NPM, so documenting the use of the polyfill can be just `require('web-monetization-polyfill')`. Looking forward to the release!

**Comment by sublimator** [comment] 2020-11-26 08:06
Nice! Thanks @wmurphyrd :)

**Comment by adrianhopebailie** [comment] 2021-02-09 10:03
@sublimator what's the status on this issue?

**Comment by sublimator** [comment] 2021-02-09 22:53
We should be publishing 0.0.52 soonish, with the new single polyfill 
Have been keeping @wmurphyrd in the loop 
You probably don't need to worry about it for your WM v2 issue roundup

**Comment by marcoscaceres** [comment] 2021-11-30 21:13
Duplicate of #29

**Closed by marcoscaceres** 2021-11-30 21:13 UTC
